; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ACTxt2Xml"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "Arondor Smart Automation"
!define PRODUCT_WEB_SITE "https://www.arondor.com/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\ACTxt2Xml.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "D:\devs\ACTxt2Xml\install\a_71x_icon.ico"
!define MUI_UNICON "D:\devs\ACTxt2Xml\install\a_71x_icon.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "C:\NSIS\Contrib\Graphics\Wizard\orange.bmp"
!define MUI_WELCOMEPAGE_TITLE "Bienvenue"
!define MUI_WELCOMEPAGE_TEXT "Installation ACTxt2Xml"
; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\bin\README.md"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "French"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "ACTxt2Xml_Install.exe"
InstallDir "c:\ACTxt2Xml"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "SectionPrincipale" SEC01

  ExecWait "sc stop ACTxt2Xml"
  ExecWait "sc delete ACTxt2Xml"
  ExecWait "$INSTDIR\bin\uninstall.bat"
  
  SetOutPath "$INSTDIR\bin"
  SetOverwrite ifnewer
  File "..\bin\uninstall.bat"
  File "..\bin\settings.json"
  File "..\bin\README.md"
  File "..\bin\NLog.dll"
  File "..\bin\NLog.config"
  File "..\bin\Newtonsoft.Json.dll"
  File "..\bin\install.bat"
  File "..\bin\ACTxt2Xml.exe.config"
  File "..\bin\ACTxt2Xml.exe"
  
  ExecWait "$INSTDIR\bin\install.bat"
  ExecWait "sc start ACTxt2Xml"

SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\ACTxt2Xml.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\ACTxt2Xml.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) a été désinstallé avec succès de votre ordinateur."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Êtes-vous certains de vouloir désinstaller totalement $(^Name) et tous ses composants ?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ExecWait "sc stop ACTxt2Xml"
  ExecWait "sc delete ACTxt2Xml"
  Delete "$INSTDIR\uninst.exe"
  RMDir /r "$INSTDIR\bin"   ; ? supprime tout le dossier bin d'un coup

  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd